spring.application.name=bot-service
server.port=8084

# Kafka consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=bot-service
spring.kafka.consumer.auto-offset-reset=earliest

# Message Service
message.service.url=http://localhost:8083

# AI
ai.api-key=${AI_API_KEY}
ai.models=nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free,google/gemma-3-4b-it:free